# Generated by Django 6.0.2 on 2026-04-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('azure', 'Azure'), ('aws', 'AWS')], max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('cpu', models.IntegerField(default=0)),
                ('mem', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('azure', 'Azure'), ('aws', 'AWS')], max_length=20)),
                ('service_name', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=20)),
                ('cost', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('provider', models.CharField(choices=[('azure', 'Azure'), ('aws', 'AWS')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
